name: CI (Tests + Optional Docker Hub Deploy)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests + coverage (no threshold)
        run: |
          pytest --cov=app --cov-report=term-missing

  docker_build_and_push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Check Docker Hub secrets exist
        id: secrets_check
        run: |
          if [ -z srinivaskamireddy ] || [ -z Srinivas@1234 ]; then
            echo "enabled=false" >> $GITHUB_OUTPUT
            echo "Docker Hub secrets missing. Skipping push."
          else
            echo "enabled=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.secrets_check.outputs.enabled == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: steps.secrets_check.outputs.enabled == 'true'
        uses: docker/login-action@v3
        with:
          username: srinivaskamireddy
          password: Srinivas@1234

      - name: Build and push
        if: steps.secrets_check.outputs.enabled == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            srinivaskamireddy/fastapi-calculator:latest
            srinivaskamireddy/fastapi-calculator:${{ github.sha }}
